# Generated by Django 6.0.4 on 2026-05-05 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('formacao', models.CharField(max_length=150)),
                ('experiencia', models.TextField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='enviada', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.curriculo')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.vaga')),
            ],
            options={
                'ordering': ['-data_candidatura'],
                'constraints': [models.UniqueConstraint(fields=('vaga', 'curriculo'), name='unique_candidatura')],
            },
        ),
    ]
